version: '3.9'

services:
  web:
    # build: ./frontend
    image: hskahlon/docker-react-frontend
    volumes:
        - .:/app
    ports:
        - "3000:3000"
    restart: always
    command: npm start
  server:
    # build: ./
    image: hskahlon/docker-mongo-backend
    container_name: myapp-node-backend
    volumes:
        - .:/app
    ports:
        - "3001:3001"
    restart: always
    environment:
        - NODE_ENV=production
    command: npm start
